name: csp_reh_katie
channels:
- conda-forge
- plotly
- r
- bokeh
- pytorch
- pyviz
- districtdatalabs
- ejolly
- defaults
dependencies:
- python=3.9
- bokeh
- sklearn-pandas
- datalad
- spyder
- scikit-learn
- nilearn
- nipype
- dash
- dash-bootstrap-components
- fastcluster
- pingouin
- mne
- tensorboardx
- yellowbrick
- pymer4
- plotly-orca
- plotly
- pytorch
- holoviews
- r-base=4.1
- r-essentials
- r-matrixstats
- r-repr
- r-devtools
- jupyterlab
- r-pma
- rtools
- pip
- pip:
  - -r requirements.txt