name: csp_surname_name
channels:
- conda-forge
- plotly
- districtdatalabs
- bokeh
- r
- ejolly
- pyviz
- defaults
dependencies:
- bokeh
- sklearn-pandas
- datalad
- spyder
- scikit-learn
- nilearn
- nipype
- dash
- dash-bootstrap-components
- fastcluster
- pingouin
- yellowbrick
- pymer4
- plotly-orca
- plotly
- holoviews
- r-base=4.1
- r-essentials
- r-matrixstats
- r-repr
- r-devtools
- jupyterlab
- r-pma
- rtools
- pip
- pip:
  - -r requirements.txt