name: csp_surname_name
channels:
- conda-forge
- plotly
- pyviz
- bokeh
- districtdatalabs
- ejolly
- pytorch
- r
- defaults
dependencies:
- arrow
- r-essentials
- r-matrixstats
- r-repr
- r-devtools
- jupyterlab
- r-base>=4.1
- r-pma
- r-dendextend
- r-circlize
- r-reticulate
- rstudio
- bokeh
- pyarrow
- sklearn-pandas
- datalad
- tableone
- spyder
- scikit-learn
- nilearn
- nipype
- dash
- dash-bootstrap-components
- statannotations
- fastcluster
- pingouin
- mne
- tensorboardx
- neurokit2
- oct2py
- yellowbrick
- pymer4
- plotly-orca
- plotly
- pytorch
- holoviews
- hvplot
- python>=3.11
- pip
- pip:
  - lckr-jupyterlab-variableinspector
  - xmltodict
  - adjustText
  - dash-cytoscape
  - brainrender
  - network_control
  - semopy
  - cca-zoo
  - bctpy
  - gemmr
  - gower
  - resample
  - antropy
  - pyvis
  - distro
  - abagen
  - openpyxl
