channels:
- conda-forge
- plotly
- bokeh
- pyviz
- defaults
dependencies:
- bokeh
- Python>=3.9
- tableone
- spyder
- scikit-learn
- nilearn
- nipype
- fastcluster
- pingouin
- plotly-orca
- plotly
- holoviews
- pip
- pip:
  - network_control
  - antropy
