name: csp_surname_name
channels:
- conda-forge
- plotly
- pyviz
- bokeh
- pytorch
- ejolly
- districtdatalabs
- defaults
dependencies:
- python=3.9
- bokeh
- sklearn-pandas
- datalad
- spyder
- scikit-learn
- nilearn
- nipype
- dash
- dash-bootstrap-components
- fastcluster
- pingouin
- mne
- tensorboardx
- neurokit2
- yellowbrick
- pymer4
- plotly-orca
- plotly
- pytorch
- holoviews
- r-base=4.1
- r-essentials
- r-matrixstats
- r-repr
- r-devtools
- jupyterlab
- r-pma
- pip
- pip:
  - -r requirements.txt